package com.doconnect.entity;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;
import java.time.LocalDateTime;


/** 

 * Answer Entity 

 * Maps to 'answers' table 

 * Represents answers to questions 

 * 

 * MAPPINGS: 

 * - ManyToOne with Question 

 * - ManyToOne with User 

 * 

 * VALIDATIONS: 

 * - Content: required, min 10 chars 

 */ 

@Entity 

@Table(name = "answers") 

@Data 

@NoArgsConstructor 

@AllArgsConstructor 

@Builder 

public class Answer { 

 

    @Id 

    @GeneratedValue( 

        strategy = GenerationType.IDENTITY) 

    private Long id; 

 

    // Answer content 

    @NotBlank(message = "Answer cannot be empty") 

    @Size(min = 10, 

        message = "Answer min 10 characters") 

    @Column(nullable = false, 

            columnDefinition = "TEXT") 

    private String content; 

 

    // Vote count 

    @Min(0) 

    @Column(nullable = false) 

    @Builder.Default 

    private int votes = 0; 

 

    // Whether this answer was accepted 

    @Column(nullable = false) 

    @Builder.Default 

    private boolean isAccepted = false; 

 

    // Whether generated by AI 

    @Column(nullable = false) 

    @Builder.Default 

    private boolean isAiGenerated = false; 

 

    @Column(name = "created_at", 

            updatable = false) 

    private LocalDateTime createdAt; 

 

    @Column(name = "updated_at") 

    private LocalDateTime updatedAt; 

 

    // Many answers belong to one question 

    @ManyToOne(fetch = FetchType.LAZY) 

    @JoinColumn(name = "question_id", 

                nullable = false) 

    @JsonIgnore 

    private Question question; 

 

    // Many answers belong to one user 

    @ManyToOne(fetch = FetchType.LAZY) 

    @JoinColumn(name = "user_id", 

                nullable = false) 

    @JsonIgnore 

    private User user; 

 

    @PrePersist 

    public void prePersist() { 

        this.createdAt = LocalDateTime.now(); 

        this.updatedAt = LocalDateTime.now(); 

    } 

 

    @PreUpdate 

    public void preUpdate() { 

        this.updatedAt = LocalDateTime.now(); 

    } 

}